[pytest]
# 指定一个或多个测试目录（相对于项目根目录）
testpaths =
    tests
# 过滤警告
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::UserWarning
# Django 配置
DJANGO_SETTINGS_MODULE = tests.test_settings
# Django 复用已有的测试数据库，跳过创建和销毁步骤
addopts = --reuse-db
# 说明：
# 	DeprecationWarning ：某个功能已被弃用，未来版本可能会移除。
# 	PendingDeprecationWarning ：某个功能即将被弃用。
# 	UserWarning ：用户定义的警告。
# 	RuntimeWarning ：运行时检测到的问题（如数值溢出）。
# 	ResourceWarning ：资源未正确释放（如文件未关闭）

