"""Django settings for article_web project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variables
env = environ.Env(
    DEBUG=(bool, False),
    # 文章扫描相关配置
    ARTICLE_GENERATED_DIR=(str, ''),
    ARTICLE_STATIC_DIR=(str, ''),
    ARTICLE_SCAN_ENABLED=(bool, True),
    ARTICLE_SCAN_INTERVAL=(int, 180),  # 默认3分钟扫描一次
)

# Take environment variables from .env file
environ.Env.read_env(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*', 'localhost', 'win.guyue.site'])
ALLOWED_HOSTS = ['*']

# Application definition
DJANGO_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'corsheaders',
    'django_extensions',
]

LOCAL_APPS = [
    'apps.articles',
    'apps.users',
    'apps.common',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise 中间件，用于静态文件服务
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.users.middleware.AuthenticationMiddleware',
    'apps.users.middleware.UserSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.users.middleware.APIResponseMiddleware',
]

ROOT_URLCONF = 'article_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'article_web.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# WhiteNoise 静态文件配置
# 启用静态文件压缩，提高传输效率
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise 配置选项
WHITENOISE_USE_FINDERS = True  # 开发环境下直接从 STATICFILES_DIRS 提供文件
WHITENOISE_AUTOREFRESH = DEBUG  # 开发环境下自动刷新静态文件
WHITENOISE_MAX_AGE = 31536000  # 静态文件缓存时间（1年）

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Auth redirect settings
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/articles/'

# Session settings
SESSION_COOKIE_AGE = 86400 * 7  # 7 days
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# API验证控制
# 是否开启API验证，如果设置为False，则所有API接口无需验证
ENABLE_API_AUTHENTICATION = os.getenv('ENABLE_API_AUTHENTICATION', 'True').lower() == 'true'

# CORS settings
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000',
    'http://127.0.0.1:3000',
])

CORS_ALLOW_CREDENTIALS = True

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# 文章扫描配置
# 文章生成目录 - 存放生成的文章文件
ARTICLE_GENERATED_DIR = env('ARTICLE_GENERATED_DIR') or str(BASE_DIR / 'generated_articles')

# 文章静态文件目录 - 存放用于下载的文章文件
ARTICLE_STATIC_DIR = env('ARTICLE_STATIC_DIR') or str(BASE_DIR / 'static' / 'file')

# 文章扫描功能是否启用
ARTICLE_SCAN_ENABLED = env('ARTICLE_SCAN_ENABLED')

# 文章扫描间隔时间（秒）
ARTICLE_SCAN_INTERVAL = env('ARTICLE_SCAN_INTERVAL')

# 确保文章相关目录存在
os.makedirs(ARTICLE_GENERATED_DIR, exist_ok=True)
os.makedirs(ARTICLE_STATIC_DIR, exist_ok=True)
ENABLE_API_AUTHENTICATION = False

# ==================== SimpleUI 配置 ====================
# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False 
SIMPLEUI_ANALYSIS = False 
# 离线模式 (不依赖外部CDN，提升内网速度)
SIMPLEUI_STATIC_OFFLINE = True
# 自定义LOGO (如果有)
# SIMPLEUI_LOGO = '/static/images/logo.png'
# 默认主题
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'
# 设置Admin站点标题
SIMPLEUI_HOME_TITLE = '控制台'
SIMPLEUI_HOME_PAGE = '/articles/admin/ai/'
SIMPLEUI_HOME_ICON = 'fas fa-desktop'
